### ISSUE TITLE
Unused size parameter in sgp41_get_serial_number() function

### ISSUE THREAD

**Issue by gabortim** [Sensirion/embedded-i2c-sgp41#2]
In the `sgp41_get_serial_number()` function, the `serial_number_size` parameter is unused:

https://github.com/Sensirion/embedded-i2c-sgp41/blob/f5e439f09cbaaf13c6a30c9788beafab1e466171/sgp41_i2c.c#L137-L161

Also it's not mentioned as a parameter in the header:
https://github.com/Sensirion/embedded-i2c-sgp41/blob/f5e439f09cbaaf13c6a30c9788beafab1e466171/sgp41_i2c.h#L117-L126

**Comment by LeonieFierz** [comment]
Thank you for reporting this inconsistency. We will fix it with a next driver update.

**Comment by psachs** [comment]
Thanks for the report, the issue is fixed
